import { AttributeStat, Quest, RecentActivityItem, CharacterProfile, InventoryItem, Achievement } from './types';
import questDeepWork from './assets/images/quest_deepwork_1789200577920.jpg';
import questMorningExercise from './assets/images/quest_gym_weights_1789201011033.jpg';
import questReadBook from './assets/images/quest_reading_1789200614011.jpg';
import questPlanDay from './assets/images/quest_plan_day_1789200935829.jpg';
import questMeditation from './assets/images/quest_meditation_1789200950636.jpg';
import questDrinkWater from './assets/images/quest_water_bottle_1789200964839.jpg';
import questCompleteAssignment from './assets/images/quest_assignment_1789200979976.jpg';
import questCleanSpace from './assets/images/quest_clean_space_1789200996914.jpg';

export const initialProfile: CharacterProfile = {
  name: 'SHADOW',
  title: 'Novice Wanderer',
  level: 0,
  health: 100,
  maxHealth: 100,
  energy: 100,
  maxEnergy: 100,
  currentXP: 0,
  maxXP: 200,
  gold: 50,
  totalXP: 0,
  streakDays: 1,
  class: 'Novice Initiate',
  equippedItems: ['trackers_blade_item', 'mindful_cloak']
};

export const initialAttributes: AttributeStat[] = [
  {
    id: 'strength',
    name: 'STRENGTH',
    current: 18,
    max: 100,
    color: '#ef4444',
    borderColor: 'border-rose-500/60',
    glowColor: 'rpg-border-glow-rose',
    barColor: 'from-rose-600 to-red-500',
    subSkills: ['Gym', 'Calisthenics', 'Heavy Training']
  },
  {
    id: 'intellect',
    name: 'INTELLECT',
    current: 16,
    max: 100,
    color: '#06b6d4',
    borderColor: 'border-cyan-500/60',
    glowColor: 'rpg-border-glow-cyan',
    barColor: 'from-cyan-600 to-sky-400',
    subSkills: ['Reading', 'Coding', 'Problem Solving']
  },
  {
    id: 'wisdom',
    name: 'WISDOM',
    current: 14,
    max: 100,
    color: '#a855f7',
    borderColor: 'border-purple-500/60',
    glowColor: 'rpg-border-glow-purple',
    barColor: 'from-purple-600 to-violet-400',
    subSkills: ['Mindfulness', 'Journaling', 'Better Decisions']
  },
  {
    id: 'discipline',
    name: 'DISCIPLINE',
    current: 20,
    max: 100,
    color: '#eab308',
    borderColor: 'border-amber-500/60',
    glowColor: 'rpg-border-glow-amber',
    barColor: 'from-amber-600 to-yellow-400',
    subSkills: ['Routine', 'Consistency', 'Self Control']
  },
  {
    id: 'vitality',
    name: 'VITALITY',
    current: 17,
    max: 100,
    color: '#10b981',
    borderColor: 'border-emerald-500/60',
    glowColor: 'rpg-border-glow-emerald',
    barColor: 'from-emerald-600 to-teal-400',
    subSkills: ['Sleep', 'Nutrition', 'Overall Health']
  }
];

export const initialQuests: Quest[] = [
  {
    id: 'quest-1',
    title: 'Deep Work Session',
    category: 'STUDY',
    categoryColor: 'bg-indigo-900/80 border-purple-400/50 text-purple-200',
    description: 'Focus for 30 minutes on a meaningful task.',
    xpReward: 250,
    goldReward: 40,
    attribute: 'intellect',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Medium',
    estimatedMinutes: 30,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“Focus is the key to extraordinary results.”',
    image: questDeepWork,
    iconName: 'book'
  },
  {
    id: 'quest-2',
    title: 'Morning Exercise',
    category: 'HEALTH',
    categoryColor: 'bg-emerald-950/80 border-emerald-400/50 text-emerald-200',
    description: 'Complete 20 min workout.',
    xpReward: 300,
    goldReward: 50,
    attribute: 'strength',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Medium',
    estimatedMinutes: 20,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“Strength doesn’t come from what you can do, but overcoming what you once thought you couldn’t.”',
    image: questMorningExercise,
    iconName: 'dumbbell'
  },
  {
    id: 'quest-3',
    title: 'Read a Book',
    category: 'PERSONAL',
    categoryColor: 'bg-amber-950/80 border-amber-400/50 text-amber-200',
    description: 'Read 20 pages.',
    xpReward: 200,
    goldReward: 30,
    attribute: 'wisdom',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Easy',
    estimatedMinutes: 25,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“A reader lives a thousand lives before he dies. The man who never reads lives only one.”',
    image: questReadBook,
    iconName: 'scroll'
  },
  {
    id: 'quest-4',
    title: 'Plan Your Day',
    category: 'WORK',
    categoryColor: 'bg-sky-950/80 border-sky-400/50 text-sky-200',
    description: 'Organize and prioritize your tasks.',
    xpReward: 150,
    goldReward: 20,
    attribute: 'discipline',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Easy',
    estimatedMinutes: 15,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“By failing to prepare, you are preparing to fail.”',
    image: questPlanDay,
    iconName: 'scroll'
  },
  {
    id: 'quest-5',
    title: 'Meditation',
    category: 'PERSONAL',
    categoryColor: 'bg-amber-950/80 border-amber-400/50 text-amber-200',
    description: 'Meditate for 10 minutes.',
    xpReward: 100,
    goldReward: 20,
    attribute: 'wisdom',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Easy',
    estimatedMinutes: 10,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“Quiet the mind, and the soul will speak.”',
    image: questMeditation,
    iconName: 'brain'
  },
  {
    id: 'quest-6',
    title: 'Drink Water',
    category: 'HEALTH',
    categoryColor: 'bg-emerald-950/80 border-emerald-400/50 text-emerald-200',
    description: 'Drink 8 glasses of water.',
    xpReward: 100,
    goldReward: 20,
    attribute: 'vitality',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Easy',
    estimatedMinutes: 12,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“Water is the driving force of all nature and energy.”',
    image: questDrinkWater,
    iconName: 'shield'
  },
  {
    id: 'quest-7',
    title: 'Complete Assignment',
    category: 'STUDY',
    categoryColor: 'bg-indigo-900/80 border-purple-400/50 text-purple-200',
    description: 'Finish your pending assignment.',
    xpReward: 200,
    goldReward: 30,
    attribute: 'intellect',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Medium',
    estimatedMinutes: 45,
    currentMinutes: 0,
    frequency: 'Weekly',
    quote: '“Small disciplines repeated with consistency lead to great achievements.”',
    image: questCompleteAssignment,
    iconName: 'book'
  },
  {
    id: 'quest-8',
    title: 'Clean Your Space',
    category: 'PERSONAL',
    categoryColor: 'bg-amber-950/80 border-amber-400/50 text-amber-200',
    description: 'Spend 15 minutes cleaning.',
    xpReward: 100,
    goldReward: 20,
    attribute: 'discipline',
    progress: 0,
    active: false,
    completed: false,
    difficulty: 'Easy',
    estimatedMinutes: 15,
    currentMinutes: 0,
    frequency: 'Daily',
    quote: '“Clear your space to clear your mind.”',
    image: questCleanSpace,
    iconName: 'shield'
  }
];

export const initialRecentActivity: RecentActivityItem[] = [
  {
    id: 'act-1',
    type: 'completed_quest',
    title: 'Completed: Deep Work Session',
    xp: 250,
    gold: 40,
    timeAgo: '2h ago',
    timestamp: Date.now() - 2 * 3600 * 1000
  },
  {
    id: 'act-2',
    type: 'achievement',
    title: 'Achievement Unlocked: Consistent Mind',
    xp: 500,
    timeAgo: '1d ago',
    timestamp: Date.now() - 24 * 3600 * 1000
  },
  {
    id: 'act-3',
    type: 'completed_quest',
    title: 'Completed: Morning Exercise',
    xp: 300,
    gold: 50,
    timeAgo: '5h ago',
    timestamp: Date.now() - 5 * 3600 * 1000
  },
  {
    id: 'act-4',
    type: 'completed_quest',
    title: 'Completed: Read a Book',
    xp: 200,
    gold: 30,
    timeAgo: '1d ago',
    timestamp: Date.now() - 26 * 3600 * 1000
  },
  {
    id: 'act-5',
    type: 'level_up',
    title: 'Levelled up to Level 12',
    timeAgo: '10h ago',
    timestamp: Date.now() - 10 * 3600 * 1000
  },
  {
    id: 'act-6',
    type: 'completed_quest',
    title: 'Completed: Plan Your Day',
    xp: 150,
    gold: 20,
    timeAgo: '2d ago',
    timestamp: Date.now() - 48 * 3600 * 1000
  }
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'mindful_cloak',
    name: 'Mindful Cloak',
    rarity: 'Epic',
    type: 'equipment',
    category: 'boosts',
    description: 'A cloak woven from the threads of focus. Helps you stay in the zone.',
    bonus: '+5 Focus while working',
    passiveEffect: 'Applies automatically while equipped',
    quote: '“Discipline wears many forms.”',
    sellPrice: 50,
    icon: 'cloak',
    quantity: 1,
    equipped: true
  },
  {
    id: 'time_shard',
    name: 'Time Shard',
    rarity: 'Legendary',
    type: 'relic',
    category: 'special',
    description: 'Crystallized temporal energy mined from deep focused states.',
    bonus: 'Reduces quest time by 25%',
    passiveEffect: 'Accelerates progress calculations',
    quote: '“Master time, or be mastered by it.”',
    sellPrice: 150,
    icon: 'hourglass',
    quantity: 0,
    equipped: false
  },
  {
    id: 'focus_potion',
    name: 'Focus Potion',
    rarity: 'Rare',
    type: 'potion',
    category: 'consumables',
    description: 'A distillation of hyper-concentration herbs that clears away brain fog.',
    bonus: '+50 Focus (1 hour)',
    quote: '“Clarity in a bottle.”',
    sellPrice: 30,
    icon: 'flask',
    quantity: 1,
    equipped: false
  },
  {
    id: 'health_potion',
    name: 'Health Potion',
    rarity: 'Common',
    type: 'potion',
    category: 'consumables',
    description: 'Enchanted tonic brewed from crimson berries and clean spring water.',
    bonus: 'Restores 20 Health',
    quote: '“Vitality renewed.”',
    sellPrice: 15,
    icon: 'apple',
    quantity: 2,
    equipped: false
  },
  {
    id: 'knowledge_tome',
    name: 'Knowledge Tome',
    rarity: 'Epic',
    type: 'relic',
    category: 'boosts',
    description: 'Illuminated codex holding synthesis techniques for complex disciplines.',
    bonus: '+5 Intellect (permanent)',
    quote: '“Knowledge compounds without limit.”',
    sellPrice: 80,
    icon: 'book',
    quantity: 0,
    equipped: false
  },
  {
    id: 'energy_bar',
    name: 'Energy Bar',
    rarity: 'Common',
    type: 'potion',
    category: 'consumables',
    description: 'Nutrient-dense ration that fuels prolonged physical and mental sessions.',
    bonus: 'Restores 20 Energy',
    quote: '“Fuel for the relentless.”',
    sellPrice: 10,
    icon: 'sneaker',
    quantity: 2,
    equipped: false
  },
  {
    id: 'phoenix_feather',
    name: 'Phoenix Feather',
    rarity: 'Rare',
    type: 'relic',
    category: 'special',
    description: 'A radiant feather imbued with perpetual flame that saves a lapsed day.',
    bonus: 'Revive streak (once)',
    quote: '“From the ashes, we rise.”',
    sellPrice: 100,
    icon: 'feather',
    quantity: 0,
    equipped: false
  },
  {
    id: 'productivity_brew',
    name: 'Productivity Brew',
    rarity: 'Common',
    type: 'potion',
    category: 'consumables',
    description: 'Dark roast coffee infused with ancient roasted beans from the highlands.',
    bonus: '+50 Focus (30 minutes)',
    quote: '“The ritual of morning execution.”',
    sellPrice: 12,
    icon: 'coffee',
    quantity: 0,
    equipped: false
  },
  {
    id: 'pathfinders_ring',
    name: "Pathfinder's Ring",
    rarity: 'Epic',
    type: 'equipment',
    category: 'boosts',
    description: 'An antique signet carrying a glowing amethyst that magnifies knowledge.',
    bonus: '+5 XP Gain (all quests)',
    passiveEffect: 'Multiplies earned experience on completion',
    quote: '“Forge uncharted ground.”',
    sellPrice: 75,
    icon: 'ring',
    quantity: 0,
    equipped: false
  },
  {
    id: 'explorers_compass',
    name: "Explorer's Compass",
    rarity: 'Rare',
    type: 'relic',
    category: 'special',
    description: 'A brass compass needle aligned with elusive milestones and rare codex pages.',
    bonus: 'Reveal hidden achievements',
    quote: '“Guidance through the fog.”',
    sellPrice: 60,
    icon: 'compass',
    quantity: 0,
    equipped: false
  },
  {
    id: 'iron_token',
    name: 'Iron Token',
    rarity: 'Common',
    type: 'relic',
    category: 'boosts',
    description: 'Heavy minted medallion symbolizing resistance drills and iron discipline.',
    bonus: '+5 Strength (permanent)',
    quote: '“The weight does not get lighter, you get stronger.”',
    sellPrice: 40,
    icon: 'dumbbell',
    quantity: 0,
    equipped: false
  },
  {
    id: 'clarity_crystal',
    name: 'Clarity Crystal',
    rarity: 'Rare',
    type: 'relic',
    category: 'boosts',
    description: 'Prismatic geode that attunes the mind to calm introspection and deep decisions.',
    bonus: '+5 Wisdom (permanent)',
    quote: '“See through the turbulence of impulse.”',
    sellPrice: 55,
    icon: 'brain',
    quantity: 0,
    equipped: false
  },
  {
    id: 'vitality_leaf',
    name: 'Vitality Leaf',
    rarity: 'Uncommon',
    type: 'potion',
    category: 'consumables',
    description: 'Dew-kissed herb harvested at dawn, rich with rejuvenating natural properties.',
    bonus: '+20 Health',
    quote: '“Nourish the biological vessel.”',
    sellPrice: 18,
    icon: 'leaf',
    quantity: 0,
    equipped: false
  },
  {
    id: 'champions_trophy',
    name: "Champion's Trophy",
    rarity: 'Epic',
    type: 'relic',
    category: 'trophies',
    description: 'Gilded cup engraved with the names of warriors who conquered their excuses.',
    bonus: 'A symbol of consistency',
    quote: '“Honor earned through the quiet days.”',
    sellPrice: 200,
    icon: 'trophy',
    quantity: 0,
    equipped: false
  },
  {
    id: 'ancient_scroll',
    name: 'Ancient Scroll',
    rarity: 'Common',
    type: 'relic',
    category: 'special',
    description: 'A mysterious scroll inscribed with ancient mantras of mastery.',
    bonus: 'A mysterious scroll...',
    quote: '“The past whispers to those who listen.”',
    sellPrice: 25,
    icon: 'scroll',
    quantity: 0,
    equipped: false
  },
  {
    id: 'streak_guardian',
    name: 'Streak Guardian',
    rarity: 'Epic',
    type: 'relic',
    category: 'trophies',
    description: 'Golden insignia commemorating two unbroken weeks of disciplined execution.',
    bonus: '+10% Streak Multiplier',
    quote: '“Unbroken cadence builds dynasties.”',
    sellPrice: 150,
    icon: 'trophy',
    quantity: 0,
    equipped: false
  },
  {
    id: 'grandmaster_badge',
    name: "Grandmaster's Seal",
    rarity: 'Legendary',
    type: 'relic',
    category: 'trophies',
    description: 'Royal crest given to champions who mastered all 5 core life attributes.',
    bonus: '+100 Max Energy Capacity',
    quote: '“The pinnacle of self mastery.”',
    sellPrice: 500,
    icon: 'trophy',
    quantity: 0,
    equipped: false
  },
  {
    id: 'trackers_blade_item',
    name: "Tracker's Blade",
    rarity: 'Rare',
    type: 'equipment',
    category: 'boosts',
    description: 'A tempered edge forged to slice away hesitation and strike directly at procrastination.',
    bonus: '+10 Discipline',
    quote: '“Strike while the iron is hot.”',
    sellPrice: 70,
    icon: 'sword',
    quantity: 1,
    equipped: true
  }
];

export const initialAchievements: Achievement[] = [
  // --- Row 1 of Reference Screenshot ---
  {
    id: 'consistent_mind',
    title: 'Consistent Mind',
    description: 'Complete 7 days in a row',
    xpReward: 500,
    goldReward: 100,
    status: 'completed',
    icon: 'brain',
    category: 'Intellect',
    rarity: 'Epic',
    quote: 'Discipline compounds.',
    unlocked: true,
    dateUnlocked: '1 day ago',
    progress: 7,
    maxProgress: 7
  },
  {
    id: 'bookworm',
    title: 'Bookworm',
    description: 'Read 10 books',
    xpReward: 300,
    goldReward: 50,
    status: 'in_progress',
    icon: 'book',
    category: 'Intellect',
    rarity: 'Rare',
    quote: 'Pages turn into wisdom.',
    unlocked: false,
    progress: 6,
    maxProgress: 10
  },
  {
    id: 'fitness_fighter',
    title: 'Fitness Fighter',
    description: 'Complete 30 workout quests',
    xpReward: 400,
    goldReward: 75,
    status: 'in_progress',
    icon: 'dumbbell',
    category: 'Strength',
    rarity: 'Rare',
    quote: 'Forge iron will through physical resistance.',
    unlocked: false,
    progress: 12,
    maxProgress: 30
  },
  {
    id: 'early_riser',
    title: 'Early Riser',
    description: 'Complete 20 morning quests',
    xpReward: 300,
    goldReward: 50,
    status: 'completed',
    icon: 'sun',
    category: 'Vitality',
    rarity: 'Rare',
    quote: 'Conquer the dawn before the world awakens.',
    unlocked: true,
    dateUnlocked: '2 days ago',
    progress: 20,
    maxProgress: 20
  },

  // --- Row 2 of Reference Screenshot ---
  {
    id: 'quest_master',
    title: 'Quest Master',
    description: 'Complete 100 total quests',
    xpReward: 1000,
    goldReward: 200,
    status: 'in_progress',
    icon: 'scroll',
    category: 'General',
    rarity: 'Legendary',
    quote: 'A century of disciplined deeds.',
    unlocked: false,
    progress: 24,
    maxProgress: 100
  },
  {
    id: 'productivity_pro',
    title: 'Productivity Pro',
    description: 'Complete 50 study quests',
    xpReward: 300,
    goldReward: 100,
    status: 'in_progress',
    icon: 'hourglass',
    category: 'Discipline',
    rarity: 'Epic',
    quote: 'Deep work yields transcendent results.',
    unlocked: false,
    progress: 18,
    maxProgress: 50
  },
  {
    id: 'health_hero',
    title: 'Health Hero',
    description: 'Complete 50 health quests',
    xpReward: 500,
    goldReward: 100,
    status: 'in_progress',
    icon: 'leaf',
    category: 'Vitality',
    rarity: 'Rare',
    quote: 'Honor the biological temple.',
    unlocked: false,
    progress: 25,
    maxProgress: 50
  },
  {
    id: 'wealth_builder',
    title: 'Wealth Builder',
    description: 'Earn 5,000 gold',
    xpReward: 750,
    goldReward: 0,
    status: 'in_progress',
    icon: 'coins',
    category: 'General',
    rarity: 'Epic',
    quote: 'Value accumulated through consistent labor.',
    unlocked: false,
    progress: 720,
    maxProgress: 5000
  },

  // --- Row 3 of Reference Screenshot (Locked) ---
  {
    id: 'legendary_discipline',
    title: 'Legendary Discipline',
    description: 'Complete 100 day streak',
    xpReward: 2000,
    goldReward: 300,
    status: 'locked',
    icon: 'flame',
    category: 'Discipline',
    rarity: 'Legendary',
    quote: 'Unbroken devotion to personal excellence.',
    unlocked: false,
    progress: 12,
    maxProgress: 100
  },
  {
    id: 'social_butterfly',
    title: 'Social Butterfly',
    description: 'Complete 25 personal quests',
    xpReward: 300,
    goldReward: 50,
    status: 'locked',
    icon: 'users',
    category: 'Personal',
    rarity: 'Common',
    quote: 'Connections enrich the hero\'s journey.',
    unlocked: false,
    progress: 8,
    maxProgress: 25
  },
  {
    id: 'explorer',
    title: 'Explorer',
    description: 'Try all quest categories',
    xpReward: 500,
    goldReward: 100,
    status: 'locked',
    icon: 'compass',
    category: 'General',
    rarity: 'Rare',
    quote: 'Venture beyond familiar territories.',
    unlocked: false,
    progress: 3,
    maxProgress: 6
  },
  {
    id: 'realm_champion',
    title: 'Realm Champion',
    description: 'Completer 250 total quests',
    xpReward: 2500,
    goldReward: 500,
    status: 'locked',
    icon: 'crown',
    category: 'General',
    rarity: 'Legendary',
    quote: 'A legend carved into the stones of the Realm.',
    unlocked: false,
    progress: 24,
    maxProgress: 250
  },

  // --- Additional Achievements matching the 25 total catalogue ---
  {
    id: 'first_steps',
    title: 'First Steps',
    description: 'Complete your first quest',
    xpReward: 100,
    goldReward: 20,
    status: 'completed',
    icon: 'footprints',
    category: 'General',
    rarity: 'Common',
    quote: 'The journey of a thousand leagues begins with a single step.',
    unlocked: true,
    dateUnlocked: '5 days ago',
    progress: 1,
    maxProgress: 1
  },
  {
    id: 'dawn_breaker',
    title: 'Dawn Breaker',
    description: 'Complete morning workouts before 8 AM for 5 days',
    xpReward: 350,
    goldReward: 40,
    status: 'completed',
    icon: 'sun',
    category: 'Vitality',
    rarity: 'Rare',
    quote: 'Greet the sunrise with exertion.',
    unlocked: true,
    dateUnlocked: '3 days ago',
    progress: 5,
    maxProgress: 5
  },
  {
    id: 'fortress_of_discipline',
    title: 'Fortress of Discipline',
    description: 'Reach Level 15 in Discipline attribute',
    xpReward: 600,
    goldReward: 80,
    status: 'completed',
    icon: 'shield',
    category: 'Discipline',
    rarity: 'Epic',
    quote: 'Unshakable boundaries create unmatched focus.',
    unlocked: true,
    dateUnlocked: '10 hours ago',
    progress: 15,
    maxProgress: 15
  },
  {
    id: 'water_monk',
    title: 'Water Monk',
    description: 'Log 8 glasses of water for 14 days',
    xpReward: 250,
    goldReward: 30,
    status: 'completed',
    icon: 'leaf',
    category: 'Vitality',
    rarity: 'Common',
    quote: 'Hydration is vitality.',
    unlocked: true,
    dateUnlocked: '4 days ago',
    progress: 14,
    maxProgress: 14
  },
  {
    id: 'deep_focus',
    title: 'Deep Focus Master',
    description: 'Complete 10 two-hour deep work sessions',
    xpReward: 800,
    goldReward: 120,
    status: 'completed',
    icon: 'brain',
    category: 'Intellect',
    rarity: 'Epic',
    quote: 'Depth over distraction.',
    unlocked: true,
    dateUnlocked: '6 days ago',
    progress: 10,
    maxProgress: 10
  },
  {
    id: 'clean_sanctuary',
    title: 'Clean Sanctuary',
    description: 'Clean personal space 7 days in a row',
    xpReward: 200,
    goldReward: 25,
    status: 'completed',
    icon: 'shield',
    category: 'Personal',
    rarity: 'Common',
    quote: 'Order in the room brings clarity to the soul.',
    unlocked: true,
    dateUnlocked: '2 days ago',
    progress: 7,
    maxProgress: 7
  },
  {
    id: 'titan_lifter',
    title: 'Titan Lifter',
    description: 'Log 50 heavy physical workout sessions',
    xpReward: 1000,
    goldReward: 150,
    status: 'in_progress',
    icon: 'dumbbell',
    category: 'Strength',
    rarity: 'Epic',
    quote: 'The bar yields to nothing but will.',
    unlocked: false,
    progress: 38,
    maxProgress: 50
  },
  {
    id: 'master_scholar',
    title: 'Master Scholar',
    description: 'Complete 30 complex study assignments',
    xpReward: 600,
    goldReward: 90,
    status: 'in_progress',
    icon: 'book',
    category: 'Intellect',
    rarity: 'Rare',
    quote: 'Understanding compounds through practice.',
    unlocked: false,
    progress: 19,
    maxProgress: 30
  },
  {
    id: 'grand_pathfinder',
    title: 'Grand Pathfinder',
    description: 'Reach Level 15 Character Rank',
    xpReward: 1500,
    goldReward: 250,
    status: 'in_progress',
    icon: 'crown',
    category: 'General',
    rarity: 'Legendary',
    quote: 'Pave the way for those who follow.',
    unlocked: false,
    progress: 12,
    maxProgress: 15
  },
  {
    id: 'iron_will',
    title: 'Iron Will',
    description: 'Complete all daily quests 30 days in a row',
    xpReward: 1800,
    goldReward: 300,
    status: 'locked',
    icon: 'shield',
    category: 'Discipline',
    rarity: 'Legendary',
    quote: 'Forged in silence, proven by time.',
    unlocked: false,
    progress: 12,
    maxProgress: 30
  },
  {
    id: 'unbroken_chain',
    title: 'Unbroken Chain',
    description: 'Reach a 365-day quest streak',
    xpReward: 5000,
    goldReward: 1000,
    status: 'locked',
    icon: 'flame',
    category: 'Discipline',
    rarity: 'Legendary',
    quote: 'A whole year of uncompromising growth.',
    unlocked: false,
    progress: 12,
    maxProgress: 365
  },
  {
    id: 'ascended_master',
    title: 'Ascended Master',
    description: 'Max out all 5 core attributes to 100',
    xpReward: 10000,
    goldReward: 2500,
    status: 'locked',
    icon: 'crown',
    category: 'General',
    rarity: 'Legendary',
    quote: 'True balance across mind, body, and spirit.',
    unlocked: false,
    progress: 20,
    maxProgress: 100
  }
];
